Repository spacetelescope/catkit, pull requests merged in 2020-09, with the labels that each got.

#109 Flip mount log messages should include in/out of beam
  catkit/hardware/thorlabs/ThorlabsMFF101.py
Labels: enhancement

#119 Update setup.py
  setup.py
Labels: build

#117 HICAT-903 Add _keep_alive to non catkit.interfaces.Instrument.Instrument subclasses
  catkit/interfaces/FlipMotor.py
Labels: HACK!, enhancement

#116 Fix for a minor issue in SNMP exception handling/logging
  catkit/hardware/SnmpUps.py
Labels: bug

#120 Bump version from v0.13.0 -> v0.14.0
  setup.py
Labels: build
