Repository spacetelescope/catkit, pull requests merged in 2020-11, with the labels that each got.

#141 CATKIT-47 Fix emulator disable_hardware string/bool bug
  catkit/emulators/iris_ao_controller.py
  catkit/util.py
Labels: bug

#142 Release v0.17.1
  setup.py
Labels: build

#143 Release v0.17.2
  setup.py
Labels: build

#144 CATKIT-50: Fix inversion of tip and tilt command
  catkit/emulators/iris_ao_controller.py
Labels: bug

#146 Release v0.17.3
  setup.py
Labels: build

#148 CATKIT-53 Add time.sleep(1) to web power switch
  catkit/hardware/WebPowerSwitch.py
Labels: bug

#149 Release v0.17.4
  setup.py
Labels: build

#150 Release v0.18.0
  setup.py
Labels: build

#152 bug fix: remove some hard-coded imports of hicat files in catkit ZWOCamera and emulator
  catkit/emulators/ZwoCamera.py
  catkit/hardware/zwo/ZwoCamera.py
Labels: bug

#153 Release v0.18.1
  setup.py
Labels: build

#147 Delete the todo in set_surface() of the IrisAO emulator, about segment numbering
  catkit/emulators/iris_ao_controller.py
Labels: IrisAO

#155 HICAT-967 Update setup-miniconda
  .github/workflows/CI.yml
Labels: CI/Test

#154 CATKIT-54 Small improvement to multiple inheritance framework
  catkit/interfaces/Instrument.py
Labels: enhancement

#156 Release v0.18.2
  setup.py
Labels: build

#157 HICAT-968 Use Python 3.7.6
  environment.yml
  setup.py
Labels: build

#160 Don't test CI against Python 3.6
  .github/workflows/CI.yml
Labels: CI/Test

#161 Release v0.19.1
  setup.py
Labels: build
