Repository spacetelescope/catkit, pull requests merged in 2021-05, with the labels that each got.

#228 HICAT-1083: Take exposures with a generator function
  catkit/hardware/zwo/ZwoCamera.py
  catkit/interfaces/Camera.py
Labels: enhancement

#233 Release v0.35.0
  setup.py
Labels: build

#236 CATKIT-96: Reduce file IO overhead for sending commands to BMC
  catkit/hardware/boston/DmCommand.py
  catkit/util.py
Labels: enhancement, performance, refactor

#235 CATKIT-95 Raise exception upon non-zero exitcode of child process
  catkit/testbed/experiment.py
Labels: bug, enhancement

#237 Release v0.35.1
  setup.py
Labels: build

#234 HICAT-793 Add shared memory management functionality
  catkit/multiprocessing.py
  catkit/testbed/caching.py
  catkit/testbed/experiment.py
  catkit/testbed/tests/test_shared_state.py
  catkit/tests/test_multiprocessing.py
  catkit/util.py
  environment.yml
Labels: new feature
