Repository spacetelescope/catkit, pull requests merged in 2021-04, with the labels that each got.

#223 CATKIT-93 Minor changes to laser stuff
  catkit/interfaces/DummyLaserSource.py
  catkit/interfaces/LaserSource.py
Labels: enhancement, refactor

#225 add docs framework
  catkit/__init__.py
  docs/api.rst
  docs/conf.py
  docs/getting_started.rst
  docs/index.rst
  docs/installation.rst
  pyproject.toml
  setup.cfg
  tox.ini
Labels: docs

#224 Add centralized way to log data from an experiment
  catkit/datalogging/README.md
  catkit/datalogging/__init__.py
  catkit/datalogging/data_log_io.py
  catkit/datalogging/data_logger.py
  catkit/datalogging/event.proto
  catkit/datalogging/event_pb2.py
  catkit/datalogging/tests/test_datalogging.py
  catkit/testbed/experiment.py
  environment.yml
Labels: enhancement

#226 Release v0.34.0
  setup.py
Labels: build

#227 HICAT-1082: Add Thorlabs power meter
  catkit/emulators/thorlabs/PM.py
  catkit/hardware/thorlabs/ThorlabsPM.py
  catkit/interfaces/PowerMeter.py
Labels: Adds Hardware

#216 Add reversed sign based on poppy version in piston too
  catkit/emulators/iris_ao_controller.py
Labels: IrisAO, bug

#231 Revert "Add reversed sign based on poppy version in piston too"
  catkit/emulators/iris_ao_controller.py
Labels: CI/Test, regression
