Repository spacetelescope/catkit, pull requests merged in 2021-02, with the labels that each got.

#190 Add code of conduct etc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: docs

#191 Fix typo in PTT111 figure
  catkit/hardware/iris_ao/figures/iris_ao_ptt111.jpg
Labels: IrisAO, docs

#189 HICAT-1014 Improved IrisAO subprocess error handling
  catkit/emulators/iris_ao_controller.py
  catkit/hardware/iris_ao/iris_ao_controller.py
  setup.py
Labels: IrisAO, enhancement

#192 CATKIT-74 4D Accufiz error handling
  catkit/emulators/accufiz.py
  catkit/hardware/FourDTechnology/Accufiz.py
Labels: enhancement

#194 CATKIT-76 Make DeviceCacheEnum mutable and add ImmutableDeviceCacheEnum
  catkit/testbed/__init__.py
  catkit/testbed/caching.py
  catkit/testbed/tests/test_testbed.py
Labels: enhancement

#195 CATKIT-76 fix regression in test
  catkit/testbed/tests/test_testbed.py
Labels: CI/Test, regression

#187 CATKIT-68: Fix IrisAO tip/tilt command signs
  catkit/emulators/iris_ao_controller.py
Labels: IrisAO

#196 CATKIT-60 Change poppy dep from develop -> v0.9.2
  environment.yml
Labels: CI/Test, build

#197 Release v0.27.0
  setup.py
Labels: build

#198 CATKIT-78 Remove testbed_state functionality and refs
  catkit/emulators/tests/conftest.py
  catkit/emulators/tests/test_emulated_boston_dm.py
  catkit/emulators/tests/test_web_power_switch.py
  catkit/hardware/__init__.py
  catkit/hardware/tests/test_testbed_state.py
Labels: DOWNstream changes needed, refactor

#200 CATKIT-20 Add and use catkit.util.sleep()
  catkit/conftest.py
  catkit/hardware/FourDTechnology/Accufiz.py
  catkit/hardware/WebPowerSwitch.py
  catkit/hardware/iris_ao/iris_ao_controller.py
  catkit/hardware/newport/NewportPicomotorController.py
  catkit/hardware/sbig/SbigCamera.py
  catkit/hardware/thorlabs/ThorlabsFW102C.py
  catkit/hardware/thorlabs/ThorlabsMCLS1.py
  catkit/hardware/thorlabs/ThorlabsMFF101.py
  catkit/hardware/thorlabs/ThorlabsTSP01.py
  catkit/tests/test_util.py
  catkit/util.py
Labels: CI/Test, enhancement

#202 HICAT-1045 Store command state in Boston object
  catkit/hardware/boston/BostonDmController.py
Labels: enhancement

#203 HICAT-1046 Store command state in Iris object
  catkit/hardware/iris_ao/iris_ao_controller.py
Labels: IrisAO, enhancement, refactor

#201 CATKIT-79: vmin and vmax in segmented DM command display()
  catkit/hardware/iris_ao/segmented_dm_command.py
Labels: IrisAO

#204 CATKIT-80 Refactor MFF101 to use Instrument interface
  catkit/emulators/thorlabs/MFF101.py
  catkit/hardware/thorlabs/ThorlabsMFF101.py
  catkit/interfaces/FlipMotor.py
Labels: DOWNstream changes needed, Does NOT impact JOST, enhancement, refactor

#205 Release v0.28.0
  setup.py
Labels: build

#206 Fix ftd2xx import for thorlabs MFF101
  catkit/emulators/tests/test_MFF101.py
  catkit/emulators/thorlabs/MFF101.py
  catkit/hardware/thorlabs/ThorlabsMFF101.py
  catkit/tests/test_all_imports.py
Labels: CI/Test, bug

#207 Release v0.28.1
  setup.py
Labels: build

#208 CATKIT-80 Fix MFF101 commanding
  catkit/emulators/thorlabs/MFF101.py
  catkit/hardware/thorlabs/ThorlabsMFF101.py
  setup.py
Labels: bug, regression
